CREATE TABLE IF NOT EXISTS `users` (
   `id` INT( 11 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
   `name` VARCHAR( 255 ) NOT NULL UNIQUE,
   `email` VARCHAR( 60 ) NOT NULL UNIQUE,
   `password` VARCHAR( 255 ) NOT NULL ,
   `active` BOOLEAN NOT NULL DEFAULT FALSE ,
   `tokenCode` VARCHAR(100) NOT NULL
);